schema = 3

[mod]
  [mod."github.com/BurntSushi/toml"]
    version = "v0.3.1"
    hash = "sha256-Rqak1dE/Aj/+Kx1/pl3Hifgt+Q3OzuZ5fJR+/x3nTbo="
  [mod."github.com/adrg/frontmatter"]
    version = "v0.2.0"
    hash = "sha256-WJsVcdCpkIkjqUz5fJOFStZYwQlrcFzQ6+mZatZiimo="
  [mod."github.com/glebarez/go-sqlite"]
    version = "v1.19.2"
    hash = "sha256-U3lYA5+b39Ghx9winKy6ybI7CdahOPTGWukOx7KVKXA="
  [mod."github.com/gomarkdown/markdown"]
    version = "v0.0.0-20221013030248-663e2500819c"
    hash = "sha256-czVkEqLaCoA6wMIVfldqOoqha4WRT7vRvRIU/5N+s3I="
  [mod."github.com/google/uuid"]
    version = "v1.3.0"
    hash = "sha256-QoR55eBtA94T2tBszyxfDtO7/pjZZSGb5vm7U0Xhs0Y="
  [mod."github.com/gorilla/mux"]
    version = "v1.8.0"
    hash = "sha256-s905hpzMH9bOLue09E2JmzPXfIS4HhAlgT7g13HCwKE="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.16"
    hash = "sha256-YMaPZvShDfA98vqw1+zWWl7M1IT4nHPGBrAt7kHo8Iw="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20200410134404-eec4a21b6bb0"
    hash = "sha256-16MkbAZXXUVbB9fObyHtQyBPqnhwNv/cjtJXrNiYAXQ="
  [mod."golang.org/x/sys"]
    version = "v0.0.0-20220811171246-fbc7d0a398ab"
    hash = "sha256-acnc9aKY/SyebObLasV+gowfB0S+6ehz3hnUgAmQmSU="
  [mod."gopkg.in/yaml.v2"]
    version = "v2.3.0"
    hash = "sha256-8tPC5nMGvUFs97W6+JXsxJLjU6EpDmPG9tXo1DyFoNU="
  [mod."modernc.org/libc"]
    version = "v1.20.3"
    hash = "sha256-NJs4hlv4dRGzBaetvUrE4HRYnw1kvr6XGpKvQE9Ivss="
  [mod."modernc.org/mathutil"]
    version = "v1.5.0"
    hash = "sha256-5xM9HjjHf9sB0vLfN53PdGpT0qPF1+KI1/lgN0/4LQo="
  [mod."modernc.org/memory"]
    version = "v1.4.0"
    hash = "sha256-x78QWQ1H82eolL7JiG6eP6l4fHhRNyIlSryQKpibcBo="
  [mod."modernc.org/sqlite"]
    version = "v1.19.2"
    hash = "sha256-KPTYF4OWbSnQv/LvCktPYyj4HxX9s5GrB+hi0x7J/CQ="
